version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres
    image: postgres:12.2
    environment: 
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"